# Generated by Django 3.2.7 on 2021-10-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_embedding',
            field=models.BinaryField(blank=True),
        ),
    ]
