# Generated by Django 3.2.7 on 2021-10-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
