# Generated by Django 3.2.7 on 2021-10-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.CharField(default='false', max_length=10),
        ),
    ]
